apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      run: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        run: cassandra
    spec:
      containers:
      - name: cassandra-container
        image: cassandra:3.11